FROM python:3.12-slim

WORKDIR /app
COPY ccm_data_model/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ccm_data_model ./ccm_data_model

USER nobody
ENTRYPOINT ["python", "-m", "ccm_data_model.ingest"]
